@startjson "Version Info"
{
    "tts_cdn_url": "http://static.duolingo.com/",
    "age_restriction_limit": 13,
    "country": "JP",
    "feature_flags": {
        "disable_avatars_global": false,
        "stories_web_maintenance": false,
        "disable_user_refreshes_for_notifications": false,
        "ios_old_user_app_rating_probability": 0.01,
        "ios_allow_gems_conversion_screen": true,
        "android_new_word_tracking_probability": 1,
        "lit_ios_use_backend": 1,
        "delay_clubs_firebase_ios": true,
        "stories_android_refresh_stories": false,
        "ios_log_json_validation_errors": 0.1,
        "web_enable_korean_from_japanese": true,
        "ios_leaderboard_session_start_refresh_probability": 0,
        "android_live_string_fetching": false,
        "fullstory_recording_sampling_rate": 0.000549368,
        "ios_track_memory_warnings": 1,
        "ios_disable_fullstory_recording_v2": false,
        "android_battery_metrics_disk_sampling_rate": 0.1,
        "asia_enable_vietnam_phone_registration": false,
        "local_grading_regression_log": true,
        "ios_smart_tips_disabled": false,
        "ios_daily_quest_goals_backend": true,
        "ios_should_reduce_experiment_requests_v2": 1,
        "alphabets_ios_maintenance": false,
        "web_frame_metrics_slow_frame_threshold": 64,
        "ios_allow_ramp_up_challenge_request": true,
        "ios_keychain_timeout_report_probability": 0.5,
        "friends_microservice_web_client": true,
        "china_asynchronous_welcome": true,
        "china_endpoint": 1,
        "opmar_ios_apple_and_social_signin_rollout": 1,
        "ios_static_network_tracking_probability": 0.1,
        "china_ios_express_connect_leaderboards": 1,
        "asia_enable_india_phone_registration": true,
        "ios_home_message_network_error_logging_probability": false,
        "ios_custom_app_rating_modal_probability_2": 0.05,
        "ios_completed_tree_app_rating_probability": 0.05,
        "ios_smart_tips_disabled_for_gapfill_challenges": false,
        "android_enable_korean": true,
        "android_disable_level_review_offline": false,
        "ios_frame_metrics_slow_frame_threshold": 64,
        "disable_grammar_skills_a2_progress_check": false,
        "stories_android_maintenance": false,
        "disable_avatars_cn": true,
        "disable_en_hi_offline_basics1_test": false,
        "ios_disable_compendium_request": false,
        "is_fullstory_recording_enabled": false,
        "android_battery_metrics_cpu_sampling_rate": 0.1,
        "android_frame_metrics_slow_frame_threshold": 64,
        "ios_custom_app_rating_modal_probability": 0,
        "android_frame_metrics_sampling_rate": 0.025,
        "android_use_onboarding_backend": true,
        "ios_track_grade_false_positive_accent_blame_probability": 1,
        "china_plus_purchase_fullstory_multiplier": 2000,
        "ios_splash_load_error_logging_probability": 0.1,
        "android_frame_threshold_demote_middle": 0.08,
        "connect_android_teams_eligibility": false,
        "china_android_timer_tracker_sampling_rate": 0.1,
        "ios_smart_tips_disabled_for_form_challenges": false,
        "china_android_enable_yunpian_login": false,
        "opmar_ios_course_picker_non_english_ui_rollout": 1,
        "android_connect_retry_profile_requests": true,
        "disable_google_recognizer": false,
        "web_enable_french_from_japanese": true,
        "year_in_review_client_entry_profile": true,
        "ios_generic_error_logging_probability": false,
        "china_android_excess_cn": true,
        "china_ios_network_tracking_probability": 0.08,
        "all_live_string_fetching": false,
        "year_in_review_client_entry_home_message": true,
        "android_leaderboards_historical_fill": 1,
        "achievements_fetch_privacy_settings": true,
        "china_ios_express_connect_achievements": 1,
        "ios_live_string_fetching": false,
        "duolingo_for_schools": true,
        "ios_enable_twitter_sharing_channel": true,
        "ios_events_enable_per_city_rollout": true,
        "ios_rollbar_report_http_unknown": false,
        "ios_frame_metrics_sampling_rate": 0.025,
        "tv_android_backend_load_shelves": true,
        "web_use_onboarding_backend": true,
        "session_end_plus_promo_rollout": false,
        "android_prefetch_all_skills_rollout": true,
        "android_token_prefill_sampling_rate": 0.01,
        "android_tts_tracking_probability": 0.0002,
        "use_newrelic_on_ios": true,
        "delay_clubs_firebase_android": false,
        "ios_attribution_device_post_rollout_ff": true,
        "china_ios_edge_gateway_endpoint": 1,
        "ios_should_reduce_experiment_requests": 0,
        "ios_literacy_ad_rollout": 1,
        "leaderboard_reactions_rollout": true,
        "china_compliance_control": true,
        "ios_china_apple_sign_in": 1,
        "web_enable_finnish_from_english": true,
        "ios_enable_latin_from_english": true,
        "midas_ios_plus_after_course_v2_rollout": 0,
        "duocon_landing_page_status": 3,
        "ios_disable_ui_strings_experiments": false,
        "ios_enable_arabic_from_english": true,
        "android_enable_arabic_from_english": true,
        "android_disable_local_notifications": false,
        "opmar_ios_course_picker_english_ui_rollout": 1,
        "china_ios_express_connect_phone_verify": 1,
        "disable_clubs_android": true,
        "china_ios_network_error_logging_probability": 0.05,
        "android_enable_podcast_season_2": true,
        "android_connect_enable_contact_sync": true,
        "web_enable_chinese_from_japanese": true,
        "web_enable_gaelic_from_english": true,
        "ios_use_onboarding_backend": true,
        "attribution_device_post_rollout_ff": true,
        "ios_timer_tracker_sampling_rate_by_country": 0.01,
        "ios_unified_session_end_eligibility": 1,
        "tv_android_backend_show_shelves": true,
        "ios_disable_skill_test_offline": false,
        "ios_achievements_v3_migration_retries": true,
        "ios_disable_attribution_config_update": false,
        "learner_speech_ios_speak_event_sample_rate": 0.1,
        "connect_android_chat_new_messages": false,
        "android_startup_task_timer_tracker_sampling_rate": 0.01,
        "android_frame_threshold_demote": 0.18,
        "ios_send_jaeger_debug_id_in_admin_requests": true,
        "stories_android_refresh_stories_on_app_start": true,
        "disable_discussions": false,
        "china_compliance_control_new": false,
        "china_android_network_tracking_probability": 0.08,
        "android_achievements_v3_migration_retries": true,
        "ios_disable_purchase_page_experiments": "",
        "android_network_tracking_probability": 0.002,
        "ios_connect_enable_contact_sync": true,
        "android_frame_threshold_promote": 0.04,
        "web_achievements_v3_migration": true,
        "ios_disable_level_review_offline": false,
        "china_ios_show_privacy_checkbox_rollout": 0,
        "web_redirect_press_microsite": true,
        "disable_ugc_cn": true,
        "enable_user_privacy_settings": true,
        "android_enable_latin_from_english": true,
        "android_tiered_rewards_probability": true,
        "ios_logout_bug_termination": 0,
        "ios_juicy_rollout": 1,
        "web_timer_tracker_sampling_rate": 0.01,
        "android_achievements_v3_migration": true,
        "web_achievements_v3_migration_retries": true,
        "android_distractor_drop_sampling_rate": 0.01,
        "ios_timer_tracker_sampling_rate": 0.01,
        "android_admin_timer_tracker_sampling_rate": 1,
        "web_enable_german_from_hungarian": true,
        "android_timer_tracker_sampling_rate": 0.01,
        "disable_clubs_ios": true,
        "ios_track_grade_missing_end_punctuation_probability": 1,
        "china_endpoint_static": 1,
        "friends_microservice_ios_client": true,
        "web_frame_metrics_sampling_rate": 0.025,
        "friends_microservice_android_client": true,
        "athena_minimum_app_version": "0.0.1.4",
        "android_static_network_tracking_probability": 0.1,
        "ios_enable_korean": true,
        "job_board": true,
        "disable_leagues_auto_refresh": false,
        "plus_purchase_fullstory_multiplier": 1,
        "allow_new_beta_applicants": true,
        "china_ios_express_connect_wechat": 1,
        "china_show_privacy_accept_page_rollout": 0,
        "ios_network_tracking_probability": 0.002,
        "clubs_firebase_event_count": 20,
        "web_enable_esperanto_from_french": true,
        "lit_ios_fullstory_rollout": 0,
        "alphabets_android_disabled": false,
        "ios_jwt_in_request_cookies": true,
        "ios_smart_tips_disabled_for_crt_challenges": false,
        "android_new_relic_fraction": 0,
        "web_enable_swedish_from_spanish": true,
        "ios_achievements_v3_migration": true,
        "china_android_tts_tracking_probability": 0.008,
        "web_enable_yiddish_from_english": true,
        "china_ios_express_connect_stories": 1,
        "disable_forum_posting": false,
        "stories_ios_maintenance": false,
        "ios_show_season_2_podcast_ad": true,
        "android_battery_metrics_memory_sampling_rate": 0.1,
        "ios_validate_plus_promo_migration": false,
        "web_enable_italian_from_german": false
    },
    "tts_base_url_http": "http://d7mj4aqfscim2.cloudfront.net/",
    "tts_voice_configuration": {
        "path": "tts/{voice}/{type}/{id}",
        "multi_voices": "{\"el\": [\"el/cora\", \"el/stefanos\"], \"en\": [\"en/miranda\", \"en/harrison\"], \"ca\": [\"ca/herena\"], \"it\": [\"it/carla\"], \"cy\": [\"cy/gwyneth\"], \"ar\": [\"ar/zeinainf\"], \"cs\": [\"cs/adina\", \"cs/jakub\"], \"id\": [\"id/eka\", \"id/ade\"], \"es\": [\"es/penelope\", \"es/miguel\"], \"zs\": [\"zs/xiuying\", \"zs/haoran\"], \"ru\": [\"ru/zoya\", \"ru/adrian\"], \"pt\": [\"pt/vitoria\", \"pt/ricardo\"], \"nb\": [\"nb/bente\", \"nb/egil\"], \"tr\": [\"tr/ecrin\", \"tr/ahmet\"], \"ro\": [\"ro/carmen\"], \"pl\": [\"pl/aniela\", \"pl/filip\"], \"dn\": [\"dn/luuk\", \"dn/eva\"], \"fr\": [\"fr/danielle\", \"fr/victor\"], \"de\": [\"de/mila\", \"de/paul\"], \"da\": [\"da/emma\", \"da/malthe\"], \"hi\": [\"hi/nikita\", \"hi/abhi\"], \"ja\": [\"ja/ichika\", \"ja/chotan\"], \"ko\": [\"ko/ahnjong\", \"ko/dae\"], \"sv\": [\"sv/astrid\"]}",
        "voices": "{\"el\": \"el/cora\", \"en\": \"en/miranda\", \"ca\": \"ca/herena\", \"it\": \"it/carla\", \"cy\": \"cy/gwyneth\", \"ar\": \"ar/zeinainf\", \"cs\": \"cs/adina\", \"id\": \"id/eka\", \"es\": \"es/penelope\", \"zs\": \"zs/xiuying\", \"ru\": \"ru/zoya\", \"pt\": \"pt/vitoria\", \"nb\": \"nb/bente\", \"tr\": \"tr/ecrin\", \"ro\": \"ro/carmen\", \"pl\": \"pl/aniela\", \"dn\": \"dn/luuk\", \"fr\": \"fr/danielle\", \"de\": \"de/mila\", \"da\": \"da/emma\", \"hi\": \"hi/nikita\", \"ja\": \"ja/ichika\", \"ko\": \"ko/ahnjong\", \"sv\": \"sv/astrid\"}"
    },
    "supported_directions": {
        "el": [
            "en"
        ],
        "en": [
            "es",
            "fr",
            "de",
            "it",
            "ja",
            "zs",
            "ru",
            "ko",
            "pt",
            "ar",
            "dn",
            "sv",
            "nb",
            "tr",
            "pl",
            "ga",
            "el",
            "he",
            "da",
            "hi",
            "cs",
            "eo",
            "uk",
            "cy",
            "vi",
            "hu",
            "sw",
            "ro",
            "id",
            "hw",
            "nv",
            "kl",
            "hv",
            "la",
            "gd",
            "fi",
            "yi"
        ],
        "vi": [
            "en",
            "zs"
        ],
        "it": [
            "en",
            "fr",
            "de",
            "es"
        ],
        "ar": [
            "en",
            "fr",
            "de",
            "sv"
        ],
        "cs": [
            "en"
        ],
        "id": [
            "en"
        ],
        "es": [
            "en",
            "fr",
            "it",
            "pt",
            "de",
            "ru",
            "ca",
            "eo",
            "gn",
            "sv"
        ],
        "zs": [
            "en",
            "es",
            "ja",
            "ko",
            "it",
            "fr"
        ],
        "ru": [
            "en",
            "de",
            "es",
            "fr"
        ],
        "pt": [
            "en",
            "es",
            "fr",
            "de",
            "it",
            "eo"
        ],
        "tr": [
            "en",
            "de",
            "ru"
        ],
        "th": [
            "en"
        ],
        "ro": [
            "en"
        ],
        "pl": [
            "en"
        ],
        "dn": [
            "en",
            "de",
            "fr"
        ],
        "fr": [
            "en",
            "es",
            "it",
            "de",
            "pt",
            "eo"
        ],
        "de": [
            "en",
            "es",
            "fr"
        ],
        "hu": [
            "en",
            "de"
        ],
        "hi": [
            "en"
        ],
        "ja": [
            "en",
            "zs",
            "ko",
            "fr"
        ],
        "ko": [
            "en"
        ],
        "uk": [
            "en"
        ]
    },
    "api_base_url": "https://api.duolingo.com",
    "offline": {
        "enabled": true,
        "max_lessons": 5
    },
    "dict_base_url": "http://d2.duolingo.com/",
    "logged_out_ab_options": {},
    "speech_host": "speech.duolingo.com",
    "tts_base_url": "https://d7mj4aqfscim2.cloudfront.net/"
}
@endjson
