name: duolingo4d
description: A most easily usable Duolingo API wrapper in Dart. With Duolingo4D, you can easily integrate your application with the Duolingo API.
version: 0.1.5
homepage: https://github.com/myConsciousness/duolingo4d

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  authorization_header: ^1.0.3
  cache_storage: ^1.0.0
  collection: ^1.15.0
  http: ^0.13.4
  json_pro: ^1.0.0
  sweet_cookie_jar: ^1.0.4
  universal_io: ^2.0.4

dev_dependencies:
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0
  test: ^1.16.0
