@startjson "Overview"
{
    "language_string": "Japanese",
    "learning_language": "ja",
    "from_language": "en",
    "language_information": {
        "pronoun_mapping": [],
        "tenses": {}
    },
    "vocab_overview": [
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "Chuang ",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Home 1",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0,
            "skill_url_title": "Home-1",
            "gender": null,
            "id": "f763b975c30e465d48f3eccbbdd8843a",
            "lexeme_id": "f763b975c30e465d48f3eccbbdd8843a",
            "word_string": "窓"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "goro",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Routines",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0,
            "skill_url_title": "Routines",
            "gender": null,
            "id": "70bde1f661078f68143e5f55da5bdb0a",
            "lexeme_id": "70bde1f661078f68143e5f55da5bdb0a",
            "word_string": "ごろ"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "ie",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Hiragana 3",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.157337,
            "skill_url_title": "Hiragana-3",
            "gender": null,
            "id": "0c10fe368ff9b64eadffda1e6a0ddcd5",
            "lexeme_id": "0c10fe368ff9b64eadffda1e6a0ddcd5",
            "word_string": "いえ"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "arigatou",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Greetings",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.012236,
            "skill_url_title": "Greetings",
            "gender": null,
            "id": "889982017051e26cca2dc4249da5a01c",
            "lexeme_id": "889982017051e26cca2dc4249da5a01c",
            "word_string": "ありがとう"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "Ren ",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Introduction",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.064665,
            "skill_url_title": "Introduction",
            "gender": null,
            "id": "807725125a1ca891bc9838e6c8525d92",
            "lexeme_id": "807725125a1ca891bc9838e6c8525d92",
            "word_string": "人"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "Liu ",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Time",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.000004,
            "skill_url_title": "Time",
            "gender": null,
            "id": "572d92749118a048e4e612e55ba35f5c",
            "lexeme_id": "572d92749118a048e4e612e55ba35f5c",
            "word_string": "六"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "yoroshiku",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Greetings",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.012236,
            "skill_url_title": "Greetings",
            "gender": null,
            "id": "310c5ff8d5355a9447c802de0c1603f5",
            "lexeme_id": "310c5ff8d5355a9447c802de0c1603f5",
            "word_string": "よろしく"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "manga",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Hiragana 4",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.157337,
            "skill_url_title": "Hiragana-4",
            "gender": null,
            "id": "d1998d48666c59a2420913da64ece90c",
            "lexeme_id": "d1998d48666c59a2420913da64ece90c",
            "word_string": "まんが"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "denwa",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Hiragana 4",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.157337,
            "skill_url_title": "Hiragana-4",
            "gender": null,
            "id": "b437d85e893330aabf9734319346cc04",
            "lexeme_id": "b437d85e893330aabf9734319346cc04",
            "word_string": "でんわ"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "are",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Food 1",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.000681,
            "skill_url_title": "Food-1",
            "gender": null,
            "id": "22da13d4007c9b4189eaa07539f116a7",
            "lexeme_id": "22da13d4007c9b4189eaa07539f116a7",
            "word_string": "あれ"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "doko",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Home 1",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0,
            "skill_url_title": "Home-1",
            "gender": null,
            "id": "093ac8d2a847d467d83ff981735d60e4",
            "lexeme_id": "093ac8d2a847d467d83ff981735d60e4",
            "word_string": "どこ"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "hoshii",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Hiragana 2",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.157337,
            "skill_url_title": "Hiragana-2",
            "gender": null,
            "id": "3d3614670741a12b9bfc2592e7d7049a",
            "lexeme_id": "3d3614670741a12b9bfc2592e7d7049a",
            "word_string": "ほしい"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "Wu Hou ",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Routines",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0,
            "skill_url_title": "Routines",
            "gender": null,
            "id": "4df2b9fa12e9a11682a73d5840a7a51c",
            "lexeme_id": "4df2b9fa12e9a11682a73d5840a7a51c",
            "word_string": "午後"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "toire",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Home 1",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0,
            "skill_url_title": "Home-1",
            "gender": null,
            "id": "fe3f10ede5fb0a6d14502c6c619c88cb",
            "lexeme_id": "fe3f10ede5fb0a6d14502c6c619c88cb",
            "word_string": "トイレ"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "ochiya",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Hiragana 4",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.157337,
            "skill_url_title": "Hiragana-4",
            "gender": null,
            "id": "26754ab1b6458bdab9aab16809a7d9b1",
            "lexeme_id": "26754ab1b6458bdab9aab16809a7d9b1",
            "word_string": "おちゃ"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "Ling ",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Routines",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0,
            "skill_url_title": "Routines",
            "gender": null,
            "id": "6fe9ea58060c2385a337ec73c374f730",
            "lexeme_id": "6fe9ea58060c2385a337ec73c374f730",
            "word_string": "零"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "Hui She ",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Routines",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0,
            "skill_url_title": "Routines",
            "gender": null,
            "id": "a138f2004a79baa8c42d2e0ad89253c6",
            "lexeme_id": "a138f2004a79baa8c42d2e0ad89253c6",
            "word_string": "会社"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "chiyoudo",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Time",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.000004,
            "skill_url_title": "Time",
            "gender": null,
            "id": "b01761eb363637b0851192aed71947db",
            "lexeme_id": "b01761eb363637b0851192aed71947db",
            "word_string": "ちょうど"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "Pu ",
            "pos": "Pronoun",
            "last_practiced_ms": 1573347371000,
            "skill": "Introduction 2",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.012236,
            "skill_url_title": "Introduction-2",
            "gender": "Masculine",
            "id": "c714ec0e478a1f1a3110288d02537b99",
            "lexeme_id": "c714ec0e478a1f1a3110288d02537b99",
            "word_string": "僕"
        },
        {
            "strength_bars": 1,
            "infinitive": null,
            "normalized_string": "natsu",
            "pos": null,
            "last_practiced_ms": 1573347371000,
            "skill": "Hiragana 3",
            "related_lexemes": [],
            "last_practiced": "2019-11-10T00:56:11Z",
            "strength": 0.157337,
            "skill_url_title": "Hiragana-3",
            "gender": null,
            "id": "e7ba0539b7e2202c47464b7e61fc7e62",
            "lexeme_id": "e7ba0539b7e2202c47464b7e61fc7e62",
            "word_string": "なつ"
        }
    ]
}
@endjson
