@startjson "Word Definition"
{
    "alternative_forms": [
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/junioren/0d7e58d30d041cd83d3c66178c35f08d",
            "text": "That is my hat.",
            "number": "singular",
            "translation_text": "それはわたしのぼうしです。",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": false,
            "translation": "それはわたしのぼうしです。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "<span class=\"highlighted\">That</span> is my hat.",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/lilyen/1cb5aef30a43863ac246dc91272f375b",
            "text": "That is an interesting question.",
            "number": "singular",
            "translation_text": "それは興味深い質問です。",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": true,
            "translation": "それは興味深い質問です。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "<span class=\"highlighted\">That</span> is an interesting question.",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/lilyen/e53fba032d44c1114a39c6b78013713f",
            "text": "That is our room.",
            "number": "singular",
            "translation_text": "あれは私たちの部屋です。",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": true,
            "translation": "あれは私たちの部屋です。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": {
                "url": "/comment/15042782",
                "num_comments": "4"
            },
            "example_sentence": "<span class=\"highlighted\">That</span> is our room.",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/zarien/95e8f5b1d0a12a248641a403b9aedbb0",
            "text": "I know that.",
            "number": "singular",
            "translation_text": "それはわかっています。",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": true,
            "translation": "それはわかっています。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "I know <span class=\"highlighted\">that</span>.",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/linen/f0595753313e08266d9c0a65c3e6a51b",
            "text": "That is your dog.",
            "number": "singular",
            "translation_text": "あれはあなたの犬です。",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": true,
            "translation": "あれはあなたの犬です。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "<span class=\"highlighted\">That</span> is your dog.",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/zarien/fa60f67e3e079440586193a6311eebae",
            "text": "That is my bag.",
            "number": "singular",
            "translation_text": "あれは私のバッグです。",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": true,
            "translation": "あれは私のバッグです。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "<span class=\"highlighted\">That</span> is my bag.",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/lilyen/b3797bf1015f19d621cdb59ae652dcec",
            "text": "That is too much.",
            "number": "singular",
            "translation_text": "それは多すぎます。",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": true,
            "translation": "それは多すぎます。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "<span class=\"highlighted\">That</span> is too much.",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/miranda/5e89b3522e0b77b84246e0a3ad536e88",
            "text": "That is a man.",
            "number": "singular",
            "translation_text": "あれは男の人です。",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": true,
            "translation": "あれは男の人です。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "<span class=\"highlighted\">That</span> is a man.",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/harrison/b7c1601ad328de79e3a5a9b2667ae26a",
            "text": "That is my horse.",
            "number": "singular",
            "translation_text": "あれは私の馬です。",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": true,
            "translation": "あれは私の馬です。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "<span class=\"highlighted\">That</span> is my horse.",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/lucyen/1925c8674c82a81fc4a07cfc5e6968a9",
            "text": "What is that?",
            "number": "singular",
            "translation_text": "それは何ですか？",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": true,
            "translation": "それは何ですか？",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "What is <span class=\"highlighted\">that</span>?",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/oscaren/7c365e179680135047e3e96958c52320",
            "text": "Who is that?",
            "number": "singular",
            "translation_text": "あれは誰ですか。",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": true,
            "translation": "あれは誰ですか。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "Who is <span class=\"highlighted\">that</span>?",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/linen/2b404631ada7e01aa89fb0ca70d8ec57",
            "text": "That is water.",
            "number": "singular",
            "translation_text": "それは水です。",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": true,
            "translation": "それは水です。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "<span class=\"highlighted\">That</span> is water.",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/lilyen/766ae2ef0774f557dc006c542fbee3bd",
            "text": "That is a bird.",
            "number": "singular",
            "translation_text": "あれは鳥です。",
            "link": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888",
            "invalid": true,
            "translation": "あれは鳥です。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "<span class=\"highlighted\">That</span> is a bird.",
            "highlighted": true,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/miranda/20f77175a87372585ae8f9eb914212e0",
            "text": "Those are my cats.",
            "number": "plural",
            "translation_text": "あれらは私の猫です。",
            "link": "/dictionary/English/those/8b4c66c452e275e8a4a66e803cc12cf9",
            "invalid": false,
            "translation": "あれらは私の猫です。",
            "case": null,
            "word": "those",
            "word_value_matched": false,
            "discussion": {
                "url": "/comment/22605572",
                "num_comments": "4"
            },
            "example_sentence": "<span class=\"highlighted\">Those</span> are my cats.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/zarien/5f4b027f80acc5c67e5fdb9626a326c3",
            "text": "Those are newspapers.",
            "number": "plural",
            "translation_text": "あれらは新聞です。",
            "link": "/dictionary/English/those/8b4c66c452e275e8a4a66e803cc12cf9",
            "invalid": true,
            "translation": "あれらは新聞です。",
            "case": null,
            "word": "those",
            "word_value_matched": false,
            "discussion": {
                "url": "/comment/8780154",
                "num_comments": "6"
            },
            "example_sentence": "<span class=\"highlighted\">Those</span> are newspapers.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/oscaren/60eb78270a6080a30bf67c074fee73e1",
            "text": "Those are horses.",
            "number": "plural",
            "translation_text": "あれらは馬です。",
            "link": "/dictionary/English/those/8b4c66c452e275e8a4a66e803cc12cf9",
            "invalid": true,
            "translation": "あれらは馬です。",
            "case": null,
            "word": "those",
            "word_value_matched": false,
            "discussion": {
                "url": "/comment/4721551",
                "num_comments": "2"
            },
            "example_sentence": "<span class=\"highlighted\">Those</span> are horses.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/oscaren/1f8d84080f8667c18c16510866e9509a",
            "text": "I want that bag.",
            "number": "singular",
            "translation_text": "私はそのバッグが欲しいです。",
            "link": "/dictionary/English/that/300f7cc3afb98d59c2a7fb1e50b8d658",
            "invalid": false,
            "translation": "私はそのバッグが欲しいです。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": {
                "url": "/comment/13373721",
                "num_comments": "2"
            },
            "example_sentence": "I want <span class=\"highlighted\">that</span> bag.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/harrison/8229bb8963abbe6e03374b5ac7b7ed3e",
            "text": "He likes that teacher.",
            "number": "singular",
            "translation_text": "彼はあの先生が好きです。",
            "link": "/dictionary/English/that/300f7cc3afb98d59c2a7fb1e50b8d658",
            "invalid": true,
            "translation": "彼はあの先生が好きです。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": {
                "url": "/comment/19339652",
                "num_comments": "2"
            },
            "example_sentence": "He likes <span class=\"highlighted\">that</span> teacher.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/eddyen/b96339446450f2c18276c8d74180acb1",
            "text": "Who is that boy?",
            "number": "singular",
            "translation_text": "あの男の子は誰ですか？",
            "link": "/dictionary/English/that/300f7cc3afb98d59c2a7fb1e50b8d658",
            "invalid": true,
            "translation": "あの男の子は誰ですか？",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": {
                "url": "/comment/16105339",
                "num_comments": "2"
            },
            "example_sentence": "Who is <span class=\"highlighted\">that</span> boy?",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/vikramen/e76ddf8b76d6710fbcac3d07ae6c62c8",
            "text": "That apple is red.",
            "number": "singular",
            "translation_text": "そのりんごは赤いです。",
            "link": "/dictionary/English/that/300f7cc3afb98d59c2a7fb1e50b8d658",
            "invalid": true,
            "translation": "そのりんごは赤いです。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "<span class=\"highlighted\">That</span> apple is red.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/lilyen/0c9a32fcf8a2ce9757f8c3fed76336c5",
            "text": "Who is that man?",
            "number": "singular",
            "translation_text": "あの男性は誰ですか？",
            "link": "/dictionary/English/that/300f7cc3afb98d59c2a7fb1e50b8d658",
            "invalid": true,
            "translation": "あの男性は誰ですか？",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": null,
            "example_sentence": "Who is <span class=\"highlighted\">that</span> man?",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/harrison/f253f5834a44b52819087ce62ef9ec29",
            "text": "That woman is a teacher.",
            "number": "singular",
            "translation_text": "あの女性は先生です。",
            "link": "/dictionary/English/that/300f7cc3afb98d59c2a7fb1e50b8d658",
            "invalid": true,
            "translation": "あの女性は先生です。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": {
                "url": "/comment/15320713",
                "num_comments": "3"
            },
            "example_sentence": "<span class=\"highlighted\">That</span> woman is a teacher.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/oscaren/d12df9d9fe4b7e58dafa88fd9bde78fa",
            "text": "That cat is black.",
            "number": "singular",
            "translation_text": "その猫は黒いです。",
            "link": "/dictionary/English/that/300f7cc3afb98d59c2a7fb1e50b8d658",
            "invalid": true,
            "translation": "その猫は黒いです。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": {
                "url": "/comment/8279244",
                "num_comments": "2"
            },
            "example_sentence": "<span class=\"highlighted\">That</span> cat is black.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/linen/dce0594dea879f883b88610c3dca7598",
            "text": "Those men are my brothers.",
            "number": "plural",
            "translation_text": "その男の人たちは私の兄弟です。",
            "link": "/dictionary/English/those/555b7154489d85bb321fc92a10fa2a7d",
            "invalid": false,
            "translation": "その男の人たちは私の兄弟です。",
            "case": null,
            "word": "those",
            "word_value_matched": false,
            "discussion": null,
            "example_sentence": "<span class=\"highlighted\">Those</span> men are my brothers.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/oscaren/a3b3306062a34f246b2552a1ade1c302",
            "text": "She likes those cats.",
            "number": "plural",
            "translation_text": "彼女はそれらの猫が好きです。",
            "link": "/dictionary/English/those/555b7154489d85bb321fc92a10fa2a7d",
            "invalid": true,
            "translation": "彼女はそれらの猫が好きです。",
            "case": null,
            "word": "those",
            "word_value_matched": false,
            "discussion": {
                "url": "/comment/10981924",
                "num_comments": "1"
            },
            "example_sentence": "She likes <span class=\"highlighted\">those</span> cats.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/lucyen/3f0adfb2d3ed6d6ff45dea51f8c5cd79",
            "text": "I like those shoes.",
            "number": "plural",
            "translation_text": "私はあれらの靴が好きです。",
            "link": "/dictionary/English/those/555b7154489d85bb321fc92a10fa2a7d",
            "invalid": true,
            "translation": "私はあれらの靴が好きです。",
            "case": null,
            "word": "those",
            "word_value_matched": false,
            "discussion": {
                "url": "/comment/13601806",
                "num_comments": "5"
            },
            "example_sentence": "I like <span class=\"highlighted\">those</span> shoes.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/harrison/9362b41e1e4a6545988998250175103f",
            "text": "Those shirts are expensive.",
            "number": "plural",
            "translation_text": "それらのシャツは高いです。",
            "link": "/dictionary/English/those/555b7154489d85bb321fc92a10fa2a7d",
            "invalid": true,
            "translation": "それらのシャツは高いです。",
            "case": null,
            "word": "those",
            "word_value_matched": false,
            "discussion": null,
            "example_sentence": "<span class=\"highlighted\">Those</span> shirts are expensive.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/linen/fc9f1aa13ee8418998d5cc6dc023ee3c",
            "text": "You know that I love dogs.",
            "number": null,
            "translation_text": "あなたは私が犬が大好きだと知っています。",
            "link": "/dictionary/English/that/ef5a4a30052d7087f01e3a863216d574",
            "invalid": false,
            "translation": "あなたは私が犬が大好きだと知っています。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": {
                "url": "/comment/8458943",
                "num_comments": "36"
            },
            "example_sentence": "You know <span class=\"highlighted\">that</span> I love dogs.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/harrison/05a597a8d7fe2a7011206bad870dbdac",
            "text": "I tell her that I eat fish.",
            "number": null,
            "translation_text": "彼女に私は魚を食べると伝えます。",
            "link": "/dictionary/English/that/ef5a4a30052d7087f01e3a863216d574",
            "invalid": true,
            "translation": "彼女に私は魚を食べると伝えます。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": {
                "url": "/comment/8458712",
                "num_comments": "14"
            },
            "example_sentence": "I tell her <span class=\"highlighted\">that</span> I eat fish.",
            "highlighted": false,
            "gender": null
        },
        {
            "tts": "https://d1vq87e9lcf771.cloudfront.net/oscaren/de02d4961e26373601584dd6471d43e4",
            "text": "She writes that she is fine.",
            "number": null,
            "translation_text": "彼女は自分は元気だと書きます。",
            "link": "/dictionary/English/that/ef5a4a30052d7087f01e3a863216d574",
            "invalid": true,
            "translation": "彼女は自分は元気だと書きます。",
            "case": null,
            "word": "that",
            "word_value_matched": true,
            "discussion": {
                "url": "/comment/9954773",
                "num_comments": "10"
            },
            "example_sentence": "She writes <span class=\"highlighted\">that</span> she is fine.",
            "highlighted": false,
            "gender": null
        }
    ],
    "has_tts": true,
    "related_discussions": [
        {
            "url": "/comment/15042782",
            "num_comments": "4",
            "anchor": "That is our room."
        },
        {
            "url": "/comment/8458943",
            "num_comments": "36",
            "anchor": "You know that I love dogs."
        },
        {
            "url": "/comment/8458712",
            "num_comments": "14",
            "anchor": "I tell her that I eat fish."
        },
        {
            "url": "/comment/9954773",
            "num_comments": "10",
            "anchor": "She writes that she is fine."
        },
        {
            "url": "/comment/8780154",
            "num_comments": "6",
            "anchor": "Those are newspapers."
        }
    ],
    "word": "that",
    "language_information": {},
    "from_language_name": "Japanese",
    "tts": "https://d1vq87e9lcf771.cloudfront.net/eddyen/2d3055aa5ee6f815bc361a15049957db",
    "infinitive": null,
    "learning_language": "en",
    "translations": "あの, その, あれ",
    "learning_language_name": "English",
    "pos": "Pronoun",
    "lexeme_image": null,
    "is_generic": false,
    "lexeme_id": "b060304086223feeab02b99b2501276b",
    "related_lexemes": [],
    "from_language": "ja",
    "canonical_path": "/dictionary/English/that/1e647900d8fa7af8417f0b93eee9f888"
}
@endjson
