@startjson "Switch Language"
{
    "streak": 0,
    "language_string": "Japanese",
    "level_progress": 40,
    "first_time": false,
    "bonus_rows": [],
    "points_rank": 1,
    "fluency_score": 0,
    "push_practice": true,
    "max_section_index": 1,
    "level_tests": [
        {
            "index": 0,
            "attempts": 3,
            "completed": false,
            "level": 6
        },
        {
            "index": 1,
            "attempts": 3,
            "completed": false,
            "level": 11
        },
        {
            "index": 2,
            "attempts": 3,
            "completed": false,
            "level": 20
        },
        {
            "index": 3,
            "attempts": 3,
            "completed": false,
            "level": 30
        },
        {
            "index": 4,
            "attempts": 3,
            "completed": false,
            "level": 41
        },
        {
            "index": 5,
            "attempts": 3,
            "completed": false,
            "level": 51
        }
    ],
    "direction_status": "released",
    "next_level": 3,
    "linkedin_share_url": "https://www.duolingo.com",
    "notify_practice": true,
    "notifications": {
        "chrome_app_ad": true,
        "net_promoter": true,
        "schools_2016_07_ad": false
    },
    "max_cefr_level": null,
    "notify_time": 780,
    "points_ranking_data": [
        {
            "username": "duovoc_tes",
            "language_string": "Japanese",
            "points_data": {
                "languages": [],
                "total": 126
            },
            "avatar": "//s3.amazonaws.com/duolingo-images/avatar/default_2",
            "language": "ja",
            "fullname": "duovoc_test",
            "id": 557897808,
            "rank": 1,
            "self": true
        }
    ],
    "num_skills_learned": 16,
    "calendar": [
        {
            "skill_id": "c63d8a5c188cda25b0544d67dc139b50",
            "improvement": 13,
            "event_type": "lesson",
            "datetime": 1631433373000
        },
        {
            "skill_id": "6e22f162b6a35046aae6caf7c2fef622",
            "improvement": 13,
            "event_type": "lesson",
            "datetime": 1631433803000
        }
    ],
    "can_transliterate": false,
    "level_left": 20,
    "no_dep": true,
    "tracking_properties": {
        "direction": "ja<-en",
        "took_placementtest": true,
        "learning_language": "ja",
        "utc_offset": 9,
        "unsafe_lexeme_restriction": false,
        "ui_language": "en",
        "max_tree_level": 10
    },
    "language_strength": 0.25,
    "next_lesson": {
        "lesson_number": 7,
        "skill_title": "Hiragana 4",
        "skill_url": "Hiragana-4"
    },
    "max_level": false,
    "level_percent": 66,
    "language": "ja",
    "level": 2,
    "skills": [
        {
            "language_string": "Japanese",
            "dependencies_name": [
                "Counting"
            ],
            "practice_recommended": false,
            "disabled": false,
            "test_count": 3,
            "missing_lessons": 6,
            "skill_progress": {
                "level": 0
            },
            "lesson": false,
            "has_explanation": true,
            "url_title": "Restaurant",
            "icon_color": "red",
            "category": "",
            "num_lessons": 6,
            "strength": 0,
            "beginner": false,
            "title": "Restaurant",
            "num_levels": 6,
            "coords_y": 11,
            "coords_x": 2,
            "progress_level_session_index": 0,
            "id": "993c25af16eb39345d13a37919868e07",
            "level_sessions_finished": 0,
            "levels_finished": 0,
            "test": true,
            "lesson_number": 1,
            "learned": false,
            "num_translation_nodes": 0,
            "achievements": [],
            "description": "",
            "index": 0,
            "bonus": false,
            "locked": true,
            "explanation": "",
            "num_lexemes": 42,
            "num_missing": 42,
            "comment_data": {},
            "dependencies": [
                "Counting"
            ],
            "known_lexemes": [],
            "words": [
                "この",
                "からい",
                "いくら",
                "メニュー",
                "レストラン",
                "円",
                "百",
                "万",
                "千",
                "その"
            ],
            "num_sessions_for_level": 6,
            "path": [],
            "strength_no_disabled_no_character": 0,
            "strength_no_disabled": 0,
            "short": "Restaurant",
            "grammar": false,
            "name": "Restaurant",
            "language": "ja",
            "is_new_grammar": false,
            "new_index": 3,
            "progress_percent": 0,
            "mastered": false
        }
    ],
    "bonus_skills": [],
    "level_points": 60,
    "all_time_rank": [
        "557897808"
    ],
    "useSmartReminderTime": true,
    "max_depth_learned": 9,
    "points": 100,
    "immersion_enabled": false,
    "points_ranking_data_dict": {
        "557897808": {
            "username": "duovoc_tes",
            "language_string": "Japanese",
            "points_data": {
                "languages": [],
                "total": 126
            },
            "avatar": "//s3.amazonaws.com/duolingo-images/avatar/default_2",
            "language": "ja",
            "fullname": "duovoc_test",
            "id": 557897808,
            "self": true
        }
    },
    "placement_test": {
        "attempts": 0
    },
    "exempt_from_health": false,
    "max_tree_level": 10
}
@endjson
